///////////////////////////////////////////////////////////////
// This is generated code. 
//////////////////////////////////////////////////////////////
// Code is generated using LLBLGen Pro version: 2.6
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates.NET20
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using Reliant.RenuOil.DAL;
using Reliant.RenuOil.DAL.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Reliant.RenuOil.DAL.FactoryClasses
{
	/// <summary>Generates IEntityFields2 instances for different kind of Entities.</summary>
	public partial class EntityFieldsFactory
	{
		/// <summary>Private CTor, no instantiation possible.</summary>
		private EntityFieldsFactory()
		{
		}

		/// <summary>General factory entrance method which will return an EntityFields object with the format generated by the factory specified</summary>
		/// <param name="relatedEntityType">The type of entity the fields are for</param>
		/// <returns>The IEntityFields2 instance requested</returns>
		public static IEntityFields2 CreateEntityFieldsObject(Reliant.RenuOil.DAL.EntityType relatedEntityType)
		{
			IEntityFields2 fieldsToReturn=null;
			IInheritanceInfoProvider inheritanceProvider = InheritanceInfoProviderSingleton.GetInstance();
			IFieldInfoProvider fieldProvider = FieldInfoProviderSingleton.GetInstance();
			switch(relatedEntityType)
			{
				case Reliant.RenuOil.DAL.EntityType.AccountEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "AccountEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.AccountEmployeeAssignmentEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "AccountEmployeeAssignmentEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.AssetCategoryEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "AssetCategoryEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.AssetReclamationServiceEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "AssetReclamationServiceEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.AssetReclamationServiceChangeLogEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "AssetReclamationServiceChangeLogEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.AssetTypeEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "AssetTypeEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.BaleEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "BaleEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.ChangeLogEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "ChangeLogEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.ChangeTypeEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "ChangeTypeEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.DeepFryerEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "DeepFryerEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.DeepFryerChangeLogEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "DeepFryerChangeLogEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.DeepFryerServiceEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "DeepFryerServiceEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.DeepFryerServiceChangeLogEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "DeepFryerServiceChangeLogEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.DockEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "DockEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.EmployeeEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "EmployeeEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.LoadEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "LoadEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.MobileDeviceEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "MobileDeviceEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.RebateEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "RebateEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.RebateTypeEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "RebateTypeEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.RecycleServiceEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "RecycleServiceEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.RecycleServiceActionEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "RecycleServiceActionEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.RecycleServiceChangeLogEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "RecycleServiceChangeLogEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.RecycleTypeEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "RecycleTypeEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.RecycleVendorEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "RecycleVendorEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.RecycleVendorServiceEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "RecycleVendorServiceEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.ServiceLocationEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "ServiceLocationEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.ServiceLocationAssetTypeEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "ServiceLocationAssetTypeEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.ServiceLocationAssetTypeChangeLogEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "ServiceLocationAssetTypeChangeLogEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.ServiceLocationEmployeeAssignmentEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "ServiceLocationEmployeeAssignmentEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.ServiceLocationRecycleTypeEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "ServiceLocationRecycleTypeEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.ServiceTypeEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "ServiceTypeEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.SettingEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "SettingEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.StatusEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "StatusEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.UserEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "UserEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.UserAccountEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "UserAccountEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.UserTypeEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "UserTypeEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.WorkOrderEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "WorkOrderEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.WorkOrderEmployeeEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "WorkOrderEmployeeEntity");
					break;
				case Reliant.RenuOil.DAL.EntityType.WorkOrderServiceLocationEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, "WorkOrderServiceLocationEntity");
					break;
			}
			return fieldsToReturn;
		}
		
		/// <summary>General method which will return an array of IEntityFieldCore objects, used by the InheritanceInfoProvider. Only the fields defined in the entity are returned, no inherited fields.</summary>
		/// <param name="entityName">the name of the entity to get the fields for. Example: "CustomerEntity"</param>
		/// <returns>array of IEntityFieldCore fields, defined in the entity with the name specified</returns>
		internal static IEntityFieldCore[] CreateFields(string entityName)
		{
			IFieldInfoProvider fieldProvider = FieldInfoProviderSingleton.GetInstance();
			return fieldProvider.GetEntityFieldsArray(entityName);
		}
		



		#region Included Code

		#endregion
	}
}
